// keywords.js

const keywords = [
    "MRT",
    "Jadwal",
    "Stasiun MRT",
    "MRT Jakarta timetable",
    "MRT Jakarta operational hours",
    "MRT Jakarta frequency",
    "MRT Jakarta peak hours",
    "MRT Jakarta off-peak hours",
    "MRT Jakarta train schedule",
    "MRT Jakarta train frequency",
    "MRT Jakarta train timetable",
    "MRT Jakarta rush hour schedule",
    "MRT Jakarta late-night schedule",
    "MRT Jakarta weekend schedule",
    "MRT Jakarta weekday schedule",
    "MRT Jakarta first train",
    "MRT Jakarta last train",
    "MRT Jakarta morning schedule",
    "MRT Jakarta evening schedule",
    "MRT Jakarta express train schedule",
    "MRT Jakarta local train schedule",
    "MRT Jakarta rapid service schedule",
    "MRT Jakarta reliable schedule",
    "Jadwal MRT Jakarta",
    "Jam operasional MRT Jakarta",
    "Frekuensi MRT Jakarta",
    "Jam sibuk MRT Jakarta",
    "Jam sepi MRT Jakarta",
    "Jadwal kereta MRT Jakarta",
    "Frekuensi kereta MRT Jakarta",
    "Jadwal kereta MRT Jakarta",
    "Jadwal puncak MRT Jakarta",
    "Jadwal larut malam MRT Jakarta",
    "Jadwal akhir pekan MRT Jakarta",
    "Jadwal hari kerja MRT Jakarta",
    "Kereta pertama MRT Jakarta",
    "Kereta terakhir MRT Jakarta",
    "Jadwal pagi MRT Jakarta",
    "Jadwal sore MRT Jakarta",
    "Jadwal kereta cepat MRT Jakarta",
    "Jadwal kereta lokal MRT Jakarta",
    "Jadwal layanan cepat MRT Jakarta",
    "Jadwal MRT Jakarta yang andal"
  ];
  
  export default keywords;
  