export const user_questions = [
    "Jadwal ke Stasiun MRT Bundaran HI?",
    "Cafe terdekat di sekitar Blok M?",
    "Bagaimana cara menuju ke Taman Ismail Marzuki menggunakan MRT?",
    "Apakah ada promo khusus untuk pengguna MRT hari ini?",
    "Berapa lama waktu tempuh dari Stasiun MRT Lebak Bulus ke Stasiun MRT Bundaran HI?",
    "Apakah ada acara atau festival di sekitar area Stasiun MRT Senayan?",
    "Apakah layanan MRT beroperasi 24 jam?",
    "Bagaimana cara menuju ke Plaza Indonesia dari Stasiun MRT Dukuh Atas?",
    "Apakah ada penutupan jalan di sekitar jalur MRT hari ini?",
    "Apakah ada penawaran diskon untuk pengguna kartu multi-trip MRT?",
    "Apa rute tercepat dari Stasiun MRT Blok M ke Stasiun MRT Bundaran HI?",
    "Apakah ada restoran makanan cepat saji di dalam stasiun MRT?",
    "Bagaimana cara menggunakan layanan WiFi di dalam kereta MRT?",
    "Apakah tersedia area parkir di dekat stasiun MRT?",
    "Apakah ada stasiun sepeda di dekat stasiun MRT?",
    "Apakah ada toilet umum di dalam stasiun MRT?",
    "Apakah ada jalur pejalan kaki yang aman dari stasiun MRT ke pusat perbelanjaan terdekat?",
    "Apakah ada area pengisian daya ponsel di dalam kereta MRT?",
    "Bagaimana cara membeli tiket MRT secara online?",
    "Apakah ada aplikasi resmi untuk memantau jadwal dan status MRT?",
    "Apakah ada kursi khusus untuk lansia atau penyandang disabilitas di dalam kereta MRT?",
    "Apakah ada area khusus untuk membawa sepeda di dalam kereta MRT?",
    "Apakah ada panduan perjalanan dalam berbagai bahasa di stasiun MRT?",
    "Apakah ada area penitipan bagasi di stasiun MRT?",
    "Apakah ada layanan taksi online yang beroperasi di dekat stasiun MRT?",
    "Apakah ada ATM di dalam stasiun MRT?",
    "Bagaimana cara menuju ke Monumen Nasional (Monas) dari stasiun MRT?",
    "Apakah ada penyedia layanan pemandu wisata di stasiun MRT?",
    "Apakah ada area untuk menyewa sepeda di dekat stasiun MRT?",
    "Apakah ada layanan antar-jemput dari stasiun MRT ke hotel terdekat?",
    "Apakah ada restoran atau tempat makan favorit di dekat stasiun MRT?",
    "Apakah ada layanan katering di dalam kereta MRT?",
]
